[project]
name = "root-project"
description = "Root Project"

version = "0.0.0"

[tool.pyright]
reportMissingTypeStubs = false
typeCheckingMode = "standard"
extraPaths = "shared"

[tool.uv.workspace]
members = [
    "apps/knowledge-base-web-crawler",
]
