[project]
name = "knowledge-base-web-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "crawl4ai>=0.7.4",
    "dotenv>=0.9.9",
    "mcp[cli]>=1.16.0",
]
